using DungeonArchitect;
using DungeonArchitect.Builders.Grid;
using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class AutoGenerateDungeon : MonoBehaviour
{
    private Dungeon dungeon;
    private MarkEmitterBossRoom dungeonSetup;
    private DungeonRuntimeNavigation navmeshGenerator;

    // Start is called before the first frame update
    void Start()
    {
        this.dungeon = GetComponent<Dungeon>();
        this.dungeonSetup = GetComponent<MarkEmitterBossRoom>();

        //this.navmeshGenerator = GetComponent<DungeonRuntimeNavigation>();
        //if (navmeshGenerator)
        //{
        //    navmeshGenerator.BuildNavMesh();
        //}
        //GenerateDungeon();
    }

    public void DestroyDungeon()
    {
        dungeon.DestroyDungeon();
    }

    public void GenerateDungeon()
    {
        if (dungeonSetup)
        {
            dungeonSetup.BossRoomCellId = -1;
            dungeonSetup.StartRoomCellId = -1;
        }
        
        dungeon.Config.Seed = (uint)(Random.value * int.MaxValue);
        //dungeon.DestroyDungeon();
        dungeon.Build();
        //StartCoroutine(_BuildDungeon());
    }
    //private IEnumerator _BuildDungeon()
    //{
    //    yield return null;
    //    dungeon.DestroyDungeon();
    //    yield return new WaitForSeconds(0.2f);
    //    yield return null;
    //    dungeon.Build();
    //    //dungeon.BuildWithCoroutine();
    //}


    // Update is called once per frame
//    void Update()
//    {
//#if UNITY_EDITOR
//        if (Input.GetKeyDown(KeyCode.Space))
//        {
//            GenerateDungeon();
//        }
//#endif
//    }

}
